
name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # adjust to your version

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(grep -oP '<Version>\K[^<]+' CmsWebApi.csproj)
          VERSION_NEW=$(echo "$VERSION" |  awk -F '.' '{$NF = $NF + 1; print}' OFS='.')
          echo "$VERSION_NEW"
   
           # Replace the version number placeholder in the csproj file
          sed -i "s/<Version>${VERSION}<\/Version>/<Version>${VERSION_NEW}<\/Version>/" CmsWebApi.csproj

      
          git config --global user.name "nandireddy12321"
          git config --global user.email "nandireddy12321@gmail.com"
          git add CmsWebApi.csproj
          git commit -m "$VERSION_NEW"
          
      - name: Push changes
        run: |
             git push https://github.com/${{ github.repository }}.git
            
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Fetch latest changes
        run: git fetch --prune --unshallow origin ${{ github.ref }}

      - name: Pull latest changes
        run: git pull origin ${{ github.ref }}

      - name: Checkout again
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Ensure you're checking out the main branch
          clean: true  # Ensure a clean checkout

      
      - name: Extract version number
        
        run: |
          VERSION=$(grep -oP '<Version>\K[^<]+' CmsWebApi.csproj)
          echo "$VERSION"

     

    
